### ISSUE TITLE
Missing dependency - natsort

### ISSUE THREAD

**Issue by wattse** [djorlando24/pySciCam#5]
Hi Both,

Suggest you update to include natsort as a dependency. On a new install of pySciCam, I receive the following error:

```python
>>> from pySciCam.pySciCam import ImageSequence
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\<path-snip>\site-packages\pySciCam\pySciCam.py", line 171, in <module>
    from natsort import natsorted
ModuleNotFoundError: No module named 'natsort'
```

**Comment by djorlando24** [comment]
Done.
